global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - follow_redirects: true
    enable_http2: true
    scheme: http
    timeout: 10s
    api_version: v2
    static_configs:
    - targets:
      - 192.168.56.139:9093
rule_files:
  - alerts.rules
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    static_configs:
      - targets:
        - 192.168.56.139:9000
      - targets:    
        - 192.168.56.139:8091
        labels:
          service: metadata
      - targets:
        - 192.168.56.139:8092
        labels:
          service: rating
      - targets:    
        - 192.168.56.139:8093
        labels:
          service: movie