apiVersion: apps/v1
kind: Deployment 
metadata:
  name: movie 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie 
  template:
    metadata:
      labels:
        app: movie 
    spec: 
      containers:
        - name: movie
          image: dockerid04352022/movie:1.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083